In [1]:
import torch
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

2.5.1+cu121
True
NVIDIA GeForce RTX 2050


## Introducing Tensors

### Creating Tensors

In [2]:
# scalars

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as a Python int
scalar.item()

7

In [5]:
# Vector - possess both maginitude and direction

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX

MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX[0]
MATRIX[1]

tensor([ 9, 10])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important, because the way many neural networks learn is that they start with tensors full of random numbers and then adjust the the random numbers to better represent the code

`start with rand num --> look at data --> update rand num --> look at data --> update rand num`

In [15]:
# create a random tensor of size (3,4)

random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.1145, 0.6181, 0.4062, 0.8206],
         [0.5737, 0.4013, 0.7569, 0.2666],
         [0.5531, 0.6887, 0.7782, 0.9758]]])

In [16]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244,244,3)) # height, width color channels - RGB
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zero and ones Tensors

In [17]:
# Create a tensor of all zeros

zero = torch.zeros(size=(3,4))
random_tensor*zero

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [18]:
# create a tensor of ones

one = torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Create range of tensors and tensors-like

In [19]:
# Using torch.arange to list a range fo numbers
one_to_ten = torch.arange(1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# Creating tensors-like to create a new tensor like another tensor

ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note** Tensor datatypes is one of the big 3 errors you will encounter with PyTorch & Deep Learning

1. Tenbsors not right datatype
2. Tensors not right shape
3. Tensors not the right device

In [21]:
# Float32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype=None,          # What datatype is the tensor
                               device=None,         # What device to execute the tensor on
                               requires_grad=False) # Whether to track gradients with tensor operations

float_32_tensor.dtype

torch.float32

In [22]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors (tensor attributes specifically)
                     
1. Tenbsors not right datatype - `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not the right device - `tensor.device`

In [24]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5886, 0.3958, 0.0762, 0.4774],
        [0.3014, 0.4808, 0.9304, 0.0041],
        [0.0629, 0.0545, 0.9079, 0.2725]])

In [25]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.5886, 0.3958, 0.0762, 0.4774],
        [0.3014, 0.4808, 0.9304, 0.0041],
        [0.0629, 0.0545, 0.9079, 0.2725]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Tensor Operations

Tensor Operations:
* Addition
* Subtraction
* Multiplication (element-wise)
* Matrix Multiplication
* Division

In [26]:
# Create tensor - Adititon

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [27]:
# Mutliplication (element-wise)

tensor * 10

tensor([10, 20, 30])

In [28]:
# Subtraction

tensor - 10

tensor([-9, -8, -7])

In [29]:
# Try out PyTorch built-in fucntions - not preferable unless dealing with larger datasets

torch.mul(tensor, 10)
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning.

1. Element-wise
2. Matrix Multiplication (dot product)

In [30]:
# Element wise multiplication

print(tensor, '*' ,tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [31]:
# Matrix Multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [32]:
# MAtrix multiplication by hand

(1*1)+(2*2)+(3*3)

14

In [33]:
# Comparing time between hand coded vs built-in torch fucntions

%%time
value = 0

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

UsageError: Line magic function `%%time` not found.


In [47]:
%%time

torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common erros in DL: shape erros

2 Main rules when following dot multiplication

1. The **inner dimensions** must match:
* `(3,2) * (3,2)` wont work
* `(3,2) * (2,3)` will work
* `(2,3) * (2,2)` will work

2. The resulting matrix has the shape fo the **outer dimensions**
* `(2,3) * (3,2)` --> `(2,2)`

In [52]:
torch.matmul(torch.rand(10,10), torch.rand(10,10)).shape

torch.Size([10, 10])

In [74]:
# Shapes for matrix multiplciation

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# To fix the tensor shape issue, manipulate shape using transpose (switches dimensions)

print(f"Original tensor_B shape: {tensor_B.shape}")
print(f"Transposed tensor_B shape: {tensor_B.T.shape}")
print(f"{tensor_A} * {tensor_B}: {torch.mm(tensor_A, tensor_B.T)}")


Original tensor_B shape: torch.Size([3, 2])
Transposed tensor_B shape: torch.Size([2, 3])
tensor([[1, 2],
        [3, 4],
        [5, 6]]) * tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]]): tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


### Finding the min, max, mean, sum (tensor aggregation)

In [76]:
x = torch.arange(0,100,10)

# find the min
torch.min(x)

tensor(0)

In [77]:
# Find the max

torch.max(x)

tensor(90)

In [83]:
# Find the mean 
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [84]:
# Find the sum

torch.sum(x)

tensor(450)

## Finding the positional min and max

In [85]:
# Find the positon in the tensor with the minimum with argmin() --> returns the index of the minimum value

x.argmin()

tensor(0)

In [87]:
# Find the positon in the tensor with the maximum with argmax() --> returns the index of the maximum value

x.argmax(), x[9]

(tensor(9), tensor(90))

In [88]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Reshaping, stacking, squeezing and unsqueezing Tensors

* Reshaping - reshapes an input tensor into a defined shape
* View - Returns a view of an inpt tensor of certain shape but kees the same memory as original tensor
* Stacking - combine multiple tensors ontop of one another (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from tensors
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with the dimensions permuted (swapped) in a certain way

In [101]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [102]:
# Add an extra dimension - dimensions need to be compatible with original size

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [105]:
# Change the view of a tensor

z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [106]:
# Changing Z changes X (because view of tensor shares the same memory as original tensor)

z[:, 0] = 5
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [115]:
# Stack tensors on top of one another

x_stacked = torch.stack([x,x,x])
x_vstacked = torch.vstack([x,x,x])
x_hstacked = torch.hstack([x,x,x])
x_hstacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [125]:
# Squeezing - removes all single dimensions from a tensor

print(f"Previous tensor shape: {x_reshaped.shape}")

print(f"Squeezed tensor shape: {x_reshaped.squeeze().shape}")

x_squeezed = x_reshaped.squeeze()

Previous tensor shape: torch.Size([1, 9])
Squeezed tensor shape: torch.Size([9])


In [130]:
# Unsqueeze - adds a single dimension to a target tensor ata a specific dimension

print(f"Previous target: {x_reshaped.squeeze()}")
print(f"Previous target shape: {x_reshaped.squeeze().shape}")

print(f"Previous target: {x_squeezed.unsqueeze(dim=0)}")
print(f"Previous target shape: {x_squeezed.unsqueeze(dim=0).shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous target shape: torch.Size([9])
Previous target: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous target shape: torch.Size([1, 9])


In [ ]:
# Permute returns the view of the original tensor but altered (all data remains the same)

x_original = torch.rand(size=(244,244,3)) # - [height, witdth, colour]

# Permute the original tensor to rearrange the dimension order

x_permuted = x_original.permute(2,0,1) # - [colour, height, width]


x_original.shape, x_permuted.shape

(torch.Size([244, 244, 3]), torch.Size([3, 244, 244]))

## Indexing (selecting data from tensors using indexing)

Index with PyTorch is similar to indexing with NumPy

In [2]:
# Create a tensor

import torch

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [6]:
# Indexing on the tensor 0th dimension - first square bracket

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
# Indexing on the tensor 1st dimension - second square bracket

x[0][0]

tensor([1, 2, 3])

In [12]:
# Indexing on the tensor 2nd dimension - first element within bracket

x[0][0][0]

tensor(1)

In [13]:
# You can also use the ":" to select all of target dimension

x[:,0]

tensor([[1, 2, 3]])

In [14]:
# Get all values of 0th dimension but only index one of the 2nd dimension

x[:,:,1]

tensor([[2, 5, 8]])

In [16]:
# Get all values of the oth dimension but only the first index value of the 1st and 2nd dimension

x[:,1,1]

tensor([5])

In [17]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension

x[0, 0,:]

tensor([1, 2, 3])

In [18]:
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch Tensors and NumPy

NumPy is a popular scientific python numeric computing library

As such PyTorch has functionality to interact with it.

* Data in NumPy but want it as PyTorch Tensor --> `torch.from_numpy(ndarray)`
* PyTorch tensor --> NumPy --> `torch.Tensor.numpy`

In [23]:
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning when converting from numpy -> torch, torch tensor will be in float64 datatype
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [24]:
# Change the value of an array

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [25]:
# Tensor to NumPy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor

In [26]:
tensor = tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility - trying to take the random out of random

In Short how a NN learns:

` start with random nums --> tensor operation --> update rand nums with better representation --> again --> again`

To reduce randomness in NN and PyTorch, comes the concept of a **random seed**

Essentially what the random seed does is flavour the randomness

In [37]:
torch.rand(3,3)

tensor([[0.9308, 0.6157, 0.2410],
        [0.8271, 0.2858, 0.7345],
        [0.4270, 0.2036, 0.8263]])

In [139]:
# Create 2 random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[9.8393e-01, 2.1359e-02, 3.4017e-01, 7.4637e-01],
        [5.2877e-01, 1.2093e-01, 6.7127e-04, 5.1953e-01],
        [1.5801e-01, 3.3034e-01, 2.1862e-01, 5.6190e-01]])
tensor([[0.8635, 0.8035, 0.0149, 0.5978],
        [0.8015, 0.7128, 0.1548, 0.1603],
        [0.0405, 0.8526, 0.5074, 0.4720]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [146]:
# Let's use random but reproducible tensors

#set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # using the notebook requires the seed to be called multiple times but is not applicable to normal scripts
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pythorch objects on GPUs for faster computation

GPUs = faster computation on numbers especially for CUDA + Nvidia + PyTorch working behind the scenes


In [69]:
!nvidia-smi

Mon Jan 13 16:43:14 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.36                 Driver Version: 566.36         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2050      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   51C    P8              1W /   45W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Check for GPU Access for PyTorch

In [148]:
# Check torch access to GPU

torch.cuda.is_available()

True

In [1]:
# setup device agnostic code -  usually at the start of your code

import torch
device = "cuda"if torch.cuda.is_available() else "cpu"

In [154]:
# Count the number of devices

torch.cuda.device_count()

1

## Putting Tensors and Models on the GPU

The reason we want tensors/ models on GPU is for faster computations



In [5]:
# create new tensor

tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [6]:
# Move tensor to GPU if available

tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)

### Moving tensors back to GPU

In [8]:
# if a tensor is on the GPU it can't be converted to NumPY

tensor_on_gpu.cpu().numpy()
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')